language: node_js
node_js:
  - '12'
cache:
  directories:
    - .test-cache
    - node_modules
    - ~/.npm
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: '12'
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        script:
          - npx semantic-release
        on:
          repo: toutpt/module-to-cdn
          branches: jmfrancois/chore/fork
